### ISSUE TITLE
Issue running Apt in webserver container

### ISSUE THREAD

**Issue by bnovick** [danpoltawski/moodle-php-apache#3]
Fixed by changing repo https to http in: 
mssql-release.list

**Comment by scara** [comment]
Hi @bnovick,
are you saying that you've edited [the content](https://github.com/danpoltawski/moodle-php-apache/blob/6efd6433097d04284d1275ae62403b005f20b322/root/tmp/setup/php-extensions.sh#L44) of https://packages.microsoft.com/config/debian/8/prod.list which is:
```
deb [arch=amd64] https://packages.microsoft.com/debian/8/prod jessie main
```
? What was the exact error on your side?

TIA,
Matteo

**Comment by bnovick** [comment]
Hi Dan,

Not necessarily an "error". It was only that I couldn't use apt-get within
the container. The error was:

"method driver /usr/lib/apt/methods/https could not be found"

I fixed by changing the call to the mentioned package to HTTP, and all
worked. Thanks!





Best,

Brandon Novick

**Comment by danpoltawski** [comment]
This is because I have tried to keep the image size down by removing things not related to the running container after installing:
https://github.com/danpoltawski/moodle-php-apache/blob/master/root/tmp/setup/php-extensions.sh#L9

I suppose in this case it makes sense to just make it permentant rather than the -dev headers

**Comment by danpoltawski** [comment]
I'm not sure if the approach is a good idea at all (removing to reduce image size) would be interested in other comments.

**Comment by scara** [comment]
+1 to keep `apt-transport-https` i.e. out of the `BUILD_PACKAGES` scope.

TIA,
Matteo

**Comment by bnovick** [comment]
Makes sense, thanks
